version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_volume/:/mosquitto/data/
    ports:
      - 9001:9001
      - 1883:1883
  nodered:
    image: nodered/node-red
    environment:
      - TZ=America/Sao_Paulo
      - NODE_RED_ENABLE_PROJECTS=true
    external_links:
      - n8n:n8n
      - elastic:elastic
      - grafana:grafana
      - mosquitto:mosquitto
    ports:
      - 1880:1880
    volumes:
      - ./node_red_volume/:/data
  n8n:
    image: n8nio/n8n
    volumes:
      - ./n8n_volume:/home/node/.n8n
    ports:
      - 1884:1884
    environment:
      N8N_PORT: 1884
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.0
    command: ["--strict.perms=false"]
    environment:
      - ELASTICSEARCH_HOST=elastic
    external_links:
      - elastic:elastic
      - mosquitto:mosquitto
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
